spring:
  application:
    name: HR-Management
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useMysqlMetadata=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useMysqlMetadata=true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

  batch:
    jdbc:
      # always -> means that we want spring batch to always initialize the schema in case if it doesn't exist,
      # never -> used when we're using migration tools to create the spring batch tables
      initialize-schema: never
    job:
      # we want to trigger the execution of the job ourselves
      # Prevents jobs from running on startup
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]