INSERT INTO departments (name) VALUES ('Software Engineering');
INSERT INTO departments (name) VALUES ('Product Management');
INSERT INTO departments (name) VALUES ('Quality Assurance');
INSERT INTO departments (name) VALUES ('DevOps & Infrastructure');
INSERT INTO departments (name) VALUES ('User Experience (UX) Design');
INSERT INTO departments (name) VALUES ('Data Science & Analytics');
INSERT INTO departments (name) VALUES ('Cybersecurity');
INSERT INTO departments (name) VALUES ('Customer Success');
INSERT INTO departments (name) VALUES ('Technical Support');
INSERT INTO departments (name) VALUES ('Sales & Business Development');
INSERT INTO departments (name) VALUES ('Marketing');
INSERT INTO departments (name) VALUES ('Human Resources');
INSERT INTO departments (name) VALUES ('Finance');
INSERT INTO departments (name) VALUES ('Legal & Compliance');
INSERT INTO departments (name) VALUES ('Project Management Office');
INSERT INTO departments (name) VALUES ('Research & Development');
INSERT INTO departments (name) VALUES ('Solutions Architecture');
INSERT INTO departments (name) VALUES ('Information Technology');
INSERT INTO departments (name) VALUES ('Professional Services');
INSERT INTO departments (name) VALUES ('Public Relations');
