INSERT INTO teams (name) VALUES ('Core Backend Squad');
INSERT INTO teams (name) VALUES ('Frontend Architects');
INSERT INTO teams (name) VALUES ('Mobile Innovators');
INSERT INTO teams (name) VALUES ('Cloud Pioneers');
INSERT INTO teams (name) VALUES ('Data Miners');
INSERT INTO teams (name) VALUES ('Security Sentinels');
INSERT INTO teams (name) VALUES ('API Integrators');
INSERT INTO teams (name) VALUES ('QA Ninjas');
INSERT INTO teams (name) VALUES ('The Debuggers');
INSERT INTO teams (name) VALUES ('AI Explorers');
INSERT INTO teams (name) VALUES ('Velocity Squad');
INSERT INTO teams (name) VALUES ('DevOps Gladiators');
INSERT INTO teams (name) VALUES ('Full Stack Fusion');
INSERT INTO teams (name) VALUES ('User Journey Map');
INSERT INTO teams (name) VALUES ('Legacy Legends');
INSERT INTO teams (name) VALUES ('Platform Reliability');
INSERT INTO teams (name) VALUES ('Agile Alchemists');
INSERT INTO teams (name) VALUES ('Code Crafters');
INSERT INTO teams (name) VALUES ('The Patch Crew');
INSERT INTO teams (name) VALUES ('Future Tech Lab');
