INSERT INTO expertises (name) VALUES ('Java Streams & Lambdas');
INSERT INTO expertises (name) VALUES ('JUnit 5 & Mockito Testing');
INSERT INTO expertises (name) VALUES ('Maven & Gradle Build Systems');
INSERT INTO expertises (name) VALUES ('REST API Basics');
INSERT INTO expertises (name) VALUES ('HTML5 & CSS3');
INSERT INTO expertises (name) VALUES ('Angular Components');
INSERT INTO expertises (name) VALUES ('Git Version Control');
INSERT INTO expertises (name) VALUES ('SQL Fundamentals');
INSERT INTO expertises (name) VALUES ('TypeScript Basics');
INSERT INTO expertises (name) VALUES ('Java Collections Framework');
INSERT INTO expertises (name) VALUES ('Spring Boot Microservices');
INSERT INTO expertises (name) VALUES ('Spring Data JPA & Hibernate');
INSERT INTO expertises (name) VALUES ('Angular Reactive Forms');
INSERT INTO expertises (name) VALUES ('Spring Security Basics');
INSERT INTO expertises (name) VALUES ('PostgreSQL Optimization');
INSERT INTO expertises (name) VALUES ('RxJS Observables');
INSERT INTO expertises (name) VALUES ('JWT Authentication');
INSERT INTO expertises (name) VALUES ('Integration Testing');
INSERT INTO expertises (name) VALUES ('Clean Code Principles');
INSERT INTO expertises (name) VALUES ('WebSockets');
INSERT INTO expertises (name) VALUES ('Docker & Kubernetes');
INSERT INTO expertises (name) VALUES ('Redis Caching Strategies');
INSERT INTO expertises (name) VALUES ('SQL Query Optimization');
INSERT INTO expertises (name) VALUES ('Spring Cloud Gateway');
INSERT INTO expertises (name) VALUES ('NoSQL Integration (MongoDB)');
INSERT INTO expertises (name) VALUES ('CI/CD Pipeline Automation');
INSERT INTO expertises (name) VALUES ('Design Patterns');
INSERT INTO expertises (name) VALUES ('State Management (NgRx)');
INSERT INTO expertises (name) VALUES ('Microservices Service Discovery');
INSERT INTO expertises (name) VALUES ('Cloud Native Development');
INSERT INTO expertises (name) VALUES ('Multi-threading & Concurrency');
INSERT INTO expertises (name) VALUES ('Apache Kafka & RabbitMQ');
INSERT INTO expertises (name) VALUES ('JVM Tuning & Garbage Collection');
INSERT INTO expertises (name) VALUES ('Aspect-Oriented Programming');
INSERT INTO expertises (name) VALUES ('System Scalability & High Availability');
INSERT INTO expertises (name) VALUES ('Event-Driven Architecture');
INSERT INTO expertises (name) VALUES ('OAuth2 & OpenID Connect');
INSERT INTO expertises (name) VALUES ('Distributed Systems Design');
INSERT INTO expertises (name) VALUES ('Infrastructure as Code');
INSERT INTO expertises (name) VALUES ('Enterprise Integration Patterns');
