-- 1. Instance Tables
CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT       NOT NULL PRIMARY KEY,
    VERSION         BIGINT DEFAULT NULL,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

-- 2. Execution Tables
CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID BIGINT      NOT NULL PRIMARY KEY,
    VERSION          BIGINT        DEFAULT NULL,
    JOB_INSTANCE_ID  BIGINT      NOT NULL,
    CREATE_TIME      TIMESTAMP(6) NOT NULL,
    START_TIME       TIMESTAMP(6)   DEFAULT NULL,
    END_TIME         TIMESTAMP(6)   DEFAULT NULL,
    STATUS           VARCHAR(10)   DEFAULT NULL,
    EXIT_CODE        VARCHAR(2500) DEFAULT NULL,
    EXIT_MESSAGE     VARCHAR(2500) DEFAULT NULL,
    LAST_UPDATED     TIMESTAMP(6)   DEFAULT NULL,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  BIGINT       NOT NULL PRIMARY KEY,
    VERSION            BIGINT       NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID   BIGINT       NOT NULL,
    CREATE_TIME        TIMESTAMP(6)  NOT NULL,
    START_TIME         TIMESTAMP(6)   DEFAULT NULL,
    END_TIME           TIMESTAMP(6)   DEFAULT NULL,
    STATUS             VARCHAR(10)   DEFAULT NULL,
    COMMIT_COUNT       BIGINT        DEFAULT NULL,
    READ_COUNT         BIGINT        DEFAULT NULL,
    FILTER_COUNT       BIGINT        DEFAULT NULL,
    WRITE_COUNT        BIGINT        DEFAULT NULL,
    READ_SKIP_COUNT    BIGINT        DEFAULT NULL,
    WRITE_SKIP_COUNT   BIGINT        DEFAULT NULL,
    PROCESS_SKIP_COUNT BIGINT        DEFAULT NULL,
    ROLLBACK_COUNT     BIGINT        DEFAULT NULL,
    EXIT_CODE          VARCHAR(2500) DEFAULT NULL,
    EXIT_MESSAGE       VARCHAR(2500) DEFAULT NULL,
    LAST_UPDATED       TIMESTAMP(6)   DEFAULT NULL,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- 3. Context & Params
CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT       NOT NULL,
    PARAMETER_NAME   VARCHAR(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500) DEFAULT NULL,
    IDENTIFYING      CHAR(1)      NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- 4. Table-backed Sequences (works on MySQL and other DBs)
CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ
(
    ID         BIGINT  NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_STEP_EXEC_SEQ_UN UNIQUE (UNIQUE_KEY)
);
INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY)
SELECT 0, '0' WHERE NOT EXISTS (SELECT 1 FROM BATCH_STEP_EXECUTION_SEQ WHERE UNIQUE_KEY='0');

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ
(
    ID         BIGINT  NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_JOB_EXEC_SEQ_UN UNIQUE (UNIQUE_KEY)
);
INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY)
SELECT 0, '0' WHERE NOT EXISTS (SELECT 1 FROM BATCH_JOB_EXECUTION_SEQ WHERE UNIQUE_KEY='0');

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ
(
    ID         BIGINT  NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_JOB_INST_SEQ_UN UNIQUE (UNIQUE_KEY)
);
INSERT INTO BATCH_JOB_INSTANCE_SEQ (ID, UNIQUE_KEY)
SELECT 0, '0' WHERE NOT EXISTS (SELECT 1 FROM BATCH_JOB_INSTANCE_SEQ WHERE UNIQUE_KEY='0');

CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ
(
    ID         BIGINT  NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT BATCH_JOB_SEQ_UN UNIQUE (UNIQUE_KEY)
);
INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY)
SELECT 0, '0' WHERE NOT EXISTS (SELECT 1 FROM BATCH_JOB_SEQ WHERE UNIQUE_KEY='0');

-- 5. Create database sequences for DBs that support them (H2, recent MySQL)

CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ START WITH 1;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ START WITH 1;